# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RFD.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RFD.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\tRFD.proto\"$\n\x0c\x42\x61tchSamples\x12\x14\n\x0c\x62\x61tchSamples\x18\x01 \x03(\x05\"\x9f\x01\n\x0bProtoBufRFD\x12\x0e\n\x06rfw_id\x18\x01 \x01(\x05\x12\x15\n\rlast_batch_id\x18\x02 \x01(\x05\x12*\n\x07samples\x18\x03 \x03(\x0b\x32\x19.ProtoBufRFD.SamplesEntry\x1a=\n\x0cSamplesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.BatchSamples:\x02\x38\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BATCHSAMPLES = _descriptor.Descriptor(
  name='BatchSamples',
  full_name='BatchSamples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='batchSamples', full_name='BatchSamples.batchSamples', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=49,
)


_PROTOBUFRFD_SAMPLESENTRY = _descriptor.Descriptor(
  name='SamplesEntry',
  full_name='ProtoBufRFD.SamplesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ProtoBufRFD.SamplesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='ProtoBufRFD.SamplesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=211,
)

_PROTOBUFRFD = _descriptor.Descriptor(
  name='ProtoBufRFD',
  full_name='ProtoBufRFD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rfw_id', full_name='ProtoBufRFD.rfw_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_batch_id', full_name='ProtoBufRFD.last_batch_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='samples', full_name='ProtoBufRFD.samples', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PROTOBUFRFD_SAMPLESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=211,
)

_PROTOBUFRFD_SAMPLESENTRY.fields_by_name['value'].message_type = _BATCHSAMPLES
_PROTOBUFRFD_SAMPLESENTRY.containing_type = _PROTOBUFRFD
_PROTOBUFRFD.fields_by_name['samples'].message_type = _PROTOBUFRFD_SAMPLESENTRY
DESCRIPTOR.message_types_by_name['BatchSamples'] = _BATCHSAMPLES
DESCRIPTOR.message_types_by_name['ProtoBufRFD'] = _PROTOBUFRFD

BatchSamples = _reflection.GeneratedProtocolMessageType('BatchSamples', (_message.Message,), dict(
  DESCRIPTOR = _BATCHSAMPLES,
  __module__ = 'RFD_pb2'
  # @@protoc_insertion_point(class_scope:BatchSamples)
  ))
_sym_db.RegisterMessage(BatchSamples)

ProtoBufRFD = _reflection.GeneratedProtocolMessageType('ProtoBufRFD', (_message.Message,), dict(

  SamplesEntry = _reflection.GeneratedProtocolMessageType('SamplesEntry', (_message.Message,), dict(
    DESCRIPTOR = _PROTOBUFRFD_SAMPLESENTRY,
    __module__ = 'RFD_pb2'
    # @@protoc_insertion_point(class_scope:ProtoBufRFD.SamplesEntry)
    ))
  ,
  DESCRIPTOR = _PROTOBUFRFD,
  __module__ = 'RFD_pb2'
  # @@protoc_insertion_point(class_scope:ProtoBufRFD)
  ))
_sym_db.RegisterMessage(ProtoBufRFD)
_sym_db.RegisterMessage(ProtoBufRFD.SamplesEntry)


_PROTOBUFRFD_SAMPLESENTRY.has_options = True
_PROTOBUFRFD_SAMPLESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
